'use client';

import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { X, Copy, Check, Download, FileText, Share2 } from 'lucide-react';
import { useReviewStore } from '../../store/useReviewStore';
import { copyToClipboard } from '../../lib/utils';

export const ExportModal: React.FC = () => {
  const { isExportOpen, setIsExportOpen, reviewResult, language, focus } = useReviewStore();
  const [copied, setCopied] = useState(false);

  if (!isExportOpen || !reviewResult) return null;

  const generateMarkdownReport = (): string => {
    const { score, summary, issues, metadata } = reviewResult;
    const dateStr = new Date().toISOString();

    let md = `## 🤖 AI Code Review Summary\n\n`;
    md += `| Overall Score | Target Language | Review Objective | Issues Found |\n`;
    md += `| :---: | :---: | :---: | :---: |\n`;
    md += `| **${score} / 100** | \`${language.toUpperCase()}\` | \`${focus.toUpperCase()}\` | **${issues.length}** |\n\n`;
    md += `### 📋 Verdict\n> ${summary}\n\n`;

    if (issues.length > 0) {
      md += `### 🔍 Detailed Findings & Patches\n\n`;
      issues.forEach((issue, idx) => {
        const icon =
          issue.severity === 'critical'
            ? '🔴 CRITICAL'
            : issue.severity === 'warning'
            ? '🟡 WARNING'
            : '🟢 SUGGESTION';

        md += `#### ${idx + 1}. [${icon}] Line ${issue.line}: ${issue.title}\n`;
        md += `**Description:** ${issue.description}\n\n`;
        if (issue.patch) {
          md += `**Remediation Patch:**\n\`\`\`${language}\n${issue.patch}\n\`\`\`\n\n`;
        }
      });
    }

    if (metadata) {
      md += `---\n*Generated by **ReviewPulse** via ${metadata.provider} (${metadata.model}) in ${metadata.processingTimeMs}ms on ${dateStr}*\n`;
    }

    return md;
  };

  const markdownContent = generateMarkdownReport();

  const handleCopyMarkdown = async () => {
    const ok = await copyToClipboard(markdownContent);
    if (ok) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownloadJSON = () => {
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(reviewResult, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `code-review-${Date.now()}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.95 }}
        className="flex max-h-[85vh] w-full max-w-2xl flex-col rounded-2xl border border-zinc-800 bg-zinc-950 p-6 shadow-2xl"
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-zinc-800/80 pb-3">
          <div className="flex items-center gap-2">
            <Share2 className="h-4 w-4 text-indigo-400" />
            <h2 className="text-sm font-semibold text-zinc-100">Export Pull Request Review</h2>
          </div>
          <button
            onClick={() => setIsExportOpen(false)}
            className="rounded-lg p-1.5 text-zinc-400 hover:bg-zinc-900 hover:text-white transition-colors"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Preview Content */}
        <div className="mt-4 flex-1 overflow-hidden flex flex-col">
          <label className="text-xs font-medium text-zinc-300 mb-1.5 flex items-center justify-between">
            <span>Markdown Preview (Ready for GitHub PR Comment):</span>
            <span className="font-mono text-[11px] text-zinc-400">{markdownContent.length} chars</span>
          </label>
          <div className="flex-1 overflow-y-auto rounded-xl border border-zinc-800/80 bg-zinc-900/60 p-3.5 font-mono text-xs text-zinc-300 whitespace-pre-wrap leading-relaxed select-all">
            {markdownContent}
          </div>
        </div>

        {/* Footer Actions */}
        <div className="mt-4 flex items-center justify-between border-t border-zinc-800/80 pt-3">
          <button
            onClick={handleDownloadJSON}
            className="flex items-center gap-1.5 rounded-lg border border-zinc-800 bg-zinc-900/60 px-3 py-1.5 text-xs font-medium text-zinc-300 hover:bg-zinc-800 hover:text-white transition-colors"
          >
            <Download className="h-3.5 w-3.5" />
            <span>Download JSON</span>
          </button>

          <div className="flex items-center gap-2">
            <button
              onClick={() => setIsExportOpen(false)}
              className="rounded-lg border border-zinc-800 bg-zinc-900/60 px-3.5 py-1.5 text-xs font-medium text-zinc-300 hover:bg-zinc-850 hover:text-white transition-colors"
            >
              Close
            </button>
            <button
              onClick={handleCopyMarkdown}
              className="flex items-center gap-1.5 rounded-lg bg-gradient-to-r from-indigo-500 to-purple-600 px-4 py-1.5 text-xs font-semibold text-white shadow-md shadow-indigo-500/20 hover:brightness-110 transition-all"
            >
              {copied ? (
                <>
                  <Check className="h-3.5 w-3.5 text-emerald-300" />
                  <span>Copied PR Comment!</span>
                </>
              ) : (
                <>
                  <Copy className="h-3.5 w-3.5" />
                  <span>Copy PR Markdown</span>
                </>
              )}
            </button>
          </div>
        </div>
      </motion.div>
    </div>
  );
};
